apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm2vec-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm2vec
  template:
    metadata:
      labels:
        app: llm2vec
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: llm2vec
        image: llm2vecregistry.azurecr.io/llm2vec:latest
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        - name: HF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llm2vec-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: llm2vec